Features
phalado/private-events pull request #1
Opened 2020-01-10 21:30 UTC by phalado

Project completed as Odin Project's requirement in https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations#project-2-private-events.

We did the "Setup and Sign in" where we created the model and controller for the Users.
In the "Basic events" we created the model and controller for creating, showing and listing events and did the association with the Users. Everything fine until here.
In the "Event Attendance" we created a model for attendance, that would be the link between users that attended in determined events and events that the users were invited for as well we modified the events to show the past and upcoming events in its show page.

2020-01-11 21:24 UTC, wathigo commented on app/controllers/events_controller.rb
> +  end
## Changes Required
### Hi guys :wave:  
I have been able to sign up successfully.
When I try to create a new event, I get this error.
![sknd](https://user-images.githubusercontent.com/44072711/72210782-a7985480-348e-11ea-9b5f-0086fd36af24.png)

2020-01-11 21:26 UTC, wathigo requested changes
## Chages Required 
Hi guys :wave:  
There is an error preventing us from creating an event.
See the comment :point_up: 

**After fixing this issue, submit another request for review.**

**Happy Coding :computer: 
Simon Wathigo**

2020-01-12 07:12 UTC, maelfosso requested changes
Hello @phalado @wathigo  :wave:
 
Nice work. I really love you ui design.
About the work, there are some things to fix in the code and a main error happening when trying to create an event

-
![Screenshot from 2020-01-12 07-56-32](https://user-images.githubusercontent.com/8848104/72215368-97c25400-3512-11ea-9442-77c0e39f2d73.png)

I think it's because the `current_user` is nill which happens because the `session[:user_id]` has not been set. I got the error when trying to create an event after **creating an user**. I suggest to use [**Gem : `byebug`**](https://github.com/deivid-rodriguez/byebug) to debug your code for a better understanding.

- Also, you forgot to set a field to the date Event in the event creation form.

- Read the comment I left below, please, to improve your work.

Kindly make those changes and submit a new code review request.
Thanks

**Mael FOSSO**
[Github](https://github.com) | [Twitter](https://twitter.com) | [LinkedIn](https://www.linkedin.com/in/mael-elvis-fosso-650b6346/)

2020-01-12 07:12 UTC, maelfosso commented on app/controllers/events_controller.rb
> +    @creator = User.find_by(id: @event.creator)
Not needed. You could directly access to the creator from `@event`

2020-01-12 07:12 UTC, maelfosso commented on app/views/events/show.html.erb
> +  <%= @creator.name%>
Just do `@event.creator.name`. It will work!

2020-01-12 07:12 UTC, maelfosso commented on app/controllers/users_controller.rb
> +    end
You can simplify this part
```ruby
@user.attended_event.upcoming_events
@user.attended_event.prev_events
```

2020-01-12 07:12 UTC, maelfosso commented on app/controllers/events_controller.rb
> +    current_user = User.find_by(id: session[:user_id])
**`OPTIONAL`**
Define a global `current_user` variable in ApplicationController and set it when the user signed so that you will use it everywhere

2020-01-13 20:01 UTC, phalado commented on app/controllers/events_controller.rb
> +    current_user = User.find_by(id: session[:user_id])
Done

2020-01-13 20:02 UTC, phalado commented on app/controllers/users_controller.rb
> +    end
Done

2020-01-13 20:13 UTC, samgaco requested changes
Hi @alexawesomecode and @phalado :high_brightness: 

There's a problem with your migrations, please fix that before continuing. 

Regards!

-----------------------

* ###### STATUS OF THE PROJECT: REQUESTED CHANGES :stop_sign:

2020-01-13 20:13 UTC, samgaco commented on db/migrate/20200109163351_add_invitation_to_user.rb
> +end
- [ ] You are adding a column to users but apparently the first migration setting up the table has been erased

2020-01-13 21:50 UTC, samgaco commented
You can move on guys :+1:

2020-01-13 21:56 UTC, merged